/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Controle.ConectaBanco;
import Controle.Controle_Treino;
import Modelos.Modelo_Tabela;
import Modelos.Modelo_Treinos;
import java.sql.*;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.border.Border;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Jean Santiago
 */
public class Treino extends javax.swing.JFrame {

    ConectaBanco conectaTreino = new ConectaBanco();
    boolean edita = false;
    boolean campoVazio = false;
    
    DateTimeFormatter formatoData = DateTimeFormatter.ofPattern("dd/MM/yyyy", Locale.forLanguageTag("pt-BR"));
    

    public Treino() {
        initComponents();
        conectaTreino.conexao();
        setSize(getWidth(), 390);
        setLocationRelativeTo(null);
        
        inicializa();
    }
    
    private void inicializa(){
        try {
            MaskFormatter dataInicio = new MaskFormatter("##/##/####");
            txtDtInicio = new JFormattedTextField(dataInicio);
        } catch (ParseException ex) {
            
        }
        
        pnlTreino.setVisible(false);
    }
    public void exportaInfoAluno(Modelo_Treinos treino) {
        idAluno.setText(String.valueOf(treino.getId_aluno()));
        nomeAluno.setText(treino.getNome());

    }

    public void preenche(String id_aluno) {

        preencherTabela("SELECT * FROM treinos WHERE fk_id_aluno = " + id_aluno);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BVermelha = new javax.swing.JTextField();
        BNormal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlTreino = new javax.swing.JPanel();
        txtDescricao = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDuracao = new javax.swing.JTextField();
        txtIDTreino = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        avisoTipo = new javax.swing.JLabel();
        avisoData = new javax.swing.JLabel();
        avisoDuracao = new javax.swing.JLabel();
        avisoDescricao = new javax.swing.JLabel();
        aviso = new javax.swing.JLabel();
        txtDtInicio = new javax.swing.JFormattedTextField();
        pnlListaTreino = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTreino = new javax.swing.JTable();
        txtAreaDescricao = new javax.swing.JTextArea();
        nomeAluno = new javax.swing.JLabel();
        idAluno = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        BVermelha.setText("jTextField1");
        BVermelha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));

        BNormal.setText("jTextField2");
        BNormal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Treinos");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Aluno:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("ID:");

        pnlTreino.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTreino.setPreferredSize(new java.awt.Dimension(440, 233));

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescricao.setRows(5);
        txtDescricao.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de treino:");
        jLabel2.setToolTipText("");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Descrição:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Data Inicio:");

        jLabel5.setText("Duração:");
        jLabel5.setToolTipText("");

        txtIDTreino.setToolTipText("");
        txtIDTreino.setEnabled(false);
        txtIDTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDTreinoActionPerformed(evt);
            }
        });

        jLabel9.setText("ID Treino");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        avisoTipo.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        avisoTipo.setForeground(new java.awt.Color(255, 0, 0));

        avisoData.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        avisoData.setForeground(new java.awt.Color(255, 0, 0));

        avisoDuracao.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        avisoDuracao.setForeground(new java.awt.Color(255, 0, 0));

        avisoDescricao.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        avisoDescricao.setForeground(new java.awt.Color(255, 0, 0));

        aviso.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        aviso.setForeground(new java.awt.Color(255, 0, 0));

        try {
            txtDtInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout pnlTreinoLayout = new javax.swing.GroupLayout(pnlTreino);
        pnlTreino.setLayout(pnlTreinoLayout);
        pnlTreinoLayout.setHorizontalGroup(
            pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTreinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTreinoLayout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnSalvar))
                    .addGroup(pnlTreinoLayout.createSequentialGroup()
                        .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTreinoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avisoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTreinoLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(avisoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTreinoLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlTreinoLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(avisoData, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlTreinoLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(avisoDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(pnlTreinoLayout.createSequentialGroup()
                                        .addComponent(txtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(pnlTreinoLayout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlTreinoLayout.createSequentialGroup()
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlTreinoLayout.setVerticalGroup(
            pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTreinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avisoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avisoData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avisoDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDuracao)
                    .addComponent(txtDtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avisoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar)
                        .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSalvar))
                .addGap(35, 35, 35))
        );

        pnlListaTreino.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Lista de treinos");
        jLabel6.setToolTipText("");
        jLabel6.setDoubleBuffered(true);

        tblTreino.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblTreino.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTreino.setGridColor(new java.awt.Color(0, 102, 102));
        tblTreino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTreinoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTreino);

        txtAreaDescricao.setColumns(20);
        txtAreaDescricao.setRows(5);

        javax.swing.GroupLayout pnlListaTreinoLayout = new javax.swing.GroupLayout(pnlListaTreino);
        pnlListaTreino.setLayout(pnlListaTreinoLayout);
        pnlListaTreinoLayout.setHorizontalGroup(
            pnlListaTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaTreinoLayout.createSequentialGroup()
                .addGroup(pnlListaTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListaTreinoLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel6)
                        .addGap(0, 139, Short.MAX_VALUE))
                    .addGroup(pnlListaTreinoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlListaTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlListaTreinoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtAreaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlListaTreinoLayout.setVerticalGroup(
            pnlListaTreinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaTreinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAreaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        nomeAluno.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        nomeAluno.setForeground(new java.awt.Color(255, 0, 0));
        nomeAluno.setToolTipText("");

        idAluno.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        idAluno.setForeground(new java.awt.Color(255, 0, 0));
        idAluno.setToolTipText("");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.setToolTipText("");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setToolTipText("");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlListaTreino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(idAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlListaTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addGap(40, 40, 40)
                .addComponent(pnlTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        pnlTreino.setVisible(true);
        pnlListaTreino.setVisible(false);
        btnAdicionar.setVisible(false);
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String tipo = txtTipo.getText().trim();
        String duracao = txtDuracao.getText().trim();
        String data = txtDtInicio.getText().trim();
        String descricao = txtDescricao.getText().trim();

        Border borda = BNormal.getBorder();
        Border vermelho = BVermelha.getBorder();

        if (tipo.isEmpty()) {
            txtTipo.setBorder(vermelho);
            avisoTipo.setText("*");
            campoVazio = true;
        } else {
            txtTipo.setBorder(borda);
            avisoTipo.setText("");
        }
        if (duracao.isEmpty()) {
            txtDuracao.setBorder(vermelho);
            avisoDuracao.setText("*");
            campoVazio = true;
        } else {
            txtDuracao.setBorder(borda);
            avisoDuracao.setText("");
        }
        if (data.isEmpty()) {
            txtDtInicio.setBorder(vermelho);
            avisoData.setText("*");
            campoVazio = true;
        } else {
            txtDtInicio.setBorder(borda);
            avisoData.setText("");
        }
        if (descricao.isEmpty()) {
            txtDescricao.setBorder(vermelho);
            avisoDescricao.setText("*");
            campoVazio = true;
        } else {
            txtDescricao.setBorder(borda);
            avisoDescricao.setText("");
        }
        if (campoVazio) {
            aviso.setText("Campos Obrigatórios: *");
            campoVazio = false;
        } else {
            aviso.setText("");

            Modelo_Treinos modTreino = new Modelo_Treinos();
            modTreino.setTipo(txtTipo.getText());
            modTreino.setDuracao(Integer.parseInt(txtDuracao.getText()));
            LocalDate dataConvertida = LocalDate.parse(txtDtInicio.getText(), formatoData);
            modTreino.setDtInicio(dataConvertida);
            modTreino.setDescricao(txtDescricao.getText());
            modTreino.setId_aluno(Integer.parseInt(idAluno.getText()));

            Controle_Treino ctrlTreino = new Controle_Treino();

            if (edita) {
                modTreino.setId_treino(Integer.parseInt(txtIDTreino.getText()));
                ctrlTreino.EditarTreino(modTreino);
            } else {
                ctrlTreino.InserirTreino(modTreino);
            }

            preencherTabela("SELECT * FROM treinos WHERE fk_id_aluno = " + idAluno.getText());

            btnAdicionar.setVisible(true);
            pnlTreino.setVisible(false);
            pnlListaTreino.setVisible(true);
            
    }//GEN-LAST:event_btnSalvarActionPerformed
    }
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        edita = true;
        int linha = tblTreino.getSelectedRow();
        txtIDTreino.setText(tblTreino.getValueAt(linha, 0).toString());
        txtTipo.setText(tblTreino.getValueAt(linha, 1).toString());
        txtDuracao.setText(tblTreino.getValueAt(linha, 2).toString());
        txtDtInicio.setText(tblTreino.getValueAt(linha, 3).toString());
        txtDescricao.setText(tblTreino.getValueAt(linha, 4).toString());
        pnlTreino.setVisible(true);
        pnlListaTreino.setVisible(false);

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int linha = tblTreino.getSelectedRow();
        txtIDTreino.setText(tblTreino.getValueAt(linha, 0).toString());
        Controle_Treino ctrlTreino = new Controle_Treino();
        ctrlTreino.ExcluirTreino(Integer.parseInt(txtIDTreino.getText()));

        txtIDTreino.setText("");

        preencherTabela("SELECT * FROM treinos WHERE fk_id_aluno = " + idAluno.getText());

        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtIDTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDTreinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDTreinoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnAdicionar.setVisible(true);
        btnExcluir.setEnabled(false);
        btnEditar.setEnabled(false);
        pnlTreino.setVisible(false);
        pnlListaTreino.setVisible(true);
        Border borda = BNormal.getBorder();
        txtTipo.setBorder(borda);
        txtDuracao.setBorder(borda);
        txtDtInicio.setBorder(borda);
        txtDescricao.setBorder(borda);
        aviso.setText("");
        avisoTipo.setText("");
        avisoDuracao.setText("");
        avisoData.setText("");
        avisoDescricao.setText("");
        campoVazio = false;
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblTreinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTreinoMouseClicked

        btnExcluir.setEnabled(true);
        btnEditar.setEnabled(true);
        int linha = tblTreino.getSelectedRow();
        conectaTreino.executaSQL("SELECT * FROM treinos WHERE id_treino = '" + tblTreino.getValueAt(linha, 0).toString() + "'");
        
        try {
            conectaTreino.rs.first();
            txtAreaDescricao.setText(conectaTreino.rs.getString("descricao"));
        } catch (SQLException ex) {
           
        }
        
    }//GEN-LAST:event_tblTreinoMouseClicked

    public void preencherTabela(String sql) {
        ArrayList dados = new ArrayList();

        String[] colunas = new String[]{"ID", "TIPO", "DURAÇÃO", "DATA_INICIO", "DESCRIÇÃO"};

        conectaTreino.executaSQL(sql);
        try {

            if (conectaTreino.rs.isBeforeFirst()) {
                conectaTreino.rs.first();
                do {
                    dados.add(new Object[]{conectaTreino.rs.getInt("id_treino"), conectaTreino.rs.getString("tipo"), conectaTreino.rs.getString("duracao"), conectaTreino.rs.getString("data_inicio"), conectaTreino.rs.getString("descricao")});
                } while (conectaTreino.rs.next());
            } else {
                JOptionPane.showMessageDialog(rootPane, "O aluno não possui treinos cadastrados");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o array list!\n ERRO: " + ex);
        }
        Modelo_Tabela modeloTreino = new Modelo_Tabela(dados, colunas);
        tblTreino.setModel(modeloTreino);
        tblTreino.getColumnModel().getColumn(0).setPreferredWidth(35);
        tblTreino.getColumnModel().getColumn(0).setResizable(false);
        tblTreino.getColumnModel().getColumn(1).setPreferredWidth(70);
        tblTreino.getColumnModel().getColumn(1).setResizable(false);
        tblTreino.getColumnModel().getColumn(2).setPreferredWidth(70);
        tblTreino.getColumnModel().getColumn(2).setResizable(false);
        tblTreino.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblTreino.getColumnModel().getColumn(3).setResizable(false);
        tblTreino.getColumnModel().getColumn(4).setPreferredWidth(144);
        tblTreino.getColumnModel().getColumn(4).setResizable(false);
        tblTreino.getTableHeader().setReorderingAllowed(false);
        tblTreino.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblTreino.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new Treino().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BNormal;
    private javax.swing.JTextField BVermelha;
    private javax.swing.JLabel aviso;
    private javax.swing.JLabel avisoData;
    private javax.swing.JLabel avisoDescricao;
    private javax.swing.JLabel avisoDuracao;
    private javax.swing.JLabel avisoTipo;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel idAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeAluno;
    private javax.swing.JPanel pnlListaTreino;
    private javax.swing.JPanel pnlTreino;
    private javax.swing.JTable tblTreino;
    private javax.swing.JTextArea txtAreaDescricao;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JFormattedTextField txtDtInicio;
    private javax.swing.JTextField txtDuracao;
    private javax.swing.JTextField txtIDTreino;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
